config/routes.rb
Rails.application.routes.draw do
  root to: 'lists#index'
  resources :lists do
    resources :bookmarks, only: [:new, :create,]
  end
  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :movie, :list, presence: true
  validates :comment, presence: true, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id, message: 'Already in the list' }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks, dependent: :destroy
  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :overview, presence: true
  validates :title, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_list, only: [:new, :create]
  before_action :set_bookmark, only: [:destroy]

  def index
    @bookmarks = Bookmark.all
  end

  def show
  end

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark.destroy
    redirect_to list_path(@bookmark)
  end

  private

  def set_list
    @list = List.find(params[:list_id])
  end

  def set_bookmark
    @bookmark = Bookmark.find(params[:id])
  end

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  before_action :set_list, only: [:edit, :show, :update, :destroy]

  def index
    @lists = List.all
  end

  def show
    @bookmark = Bookmark.new
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @list.destroy
    redirect_to list_path(@list)
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/_form.html.erb
<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.input :comment %>
  <%= f.association :movie %>
  <%= f.submit class: 'btn-submit mt-3' %>
<% end %>

app/views/bookmarks/new.html.erb
<div class="container">
  <div class="">
    <div class="row new-form">
      <div class="col-lg-6 left-bg-list">
      </div>
      <div class="col-lg-6 right-bg" >
        <%= render 'form', bookmark: @bookmark %>
      </div>
    </div>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="banner mb-5" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://dirprodformations.fr/wp-content/uploads/2017/08/salle-cinema-3.jpg);">
  <div class="container">
    <h1><strong>Save any kind of movies</strong>! </h1>
     <%= link_to "Add a new list", new_list_path(@bookmark), class:"btn btn-gradient" %>
         <span class="click">
          </span>
  </div>
</div>
<div class="movie-category">
  <h1 class="category-title">MY LISTS :</h1>
</div>




  <div class="row">
    <% @lists.each do |list| %>
    <div class="col-3 bg-success m-3">
      <h3 class="list-title"><%= link_to list.name, list_path(list) %></h3>
      <p><%= link_to "Delete", list_path(list), data: { turbo_method: :delete, turbo_confirm: "Are you sure" }, class: 'btn-delete'%></p>

    </div>
      <% end %>
  </div>

app/views/lists/new.html.erb
<h1>Add your new movie below:</h1>
<%= simple_form_for @list do |f| %>
  <%= f.input :name, placeholder: "Write the movie name here" %>
  <%= f.submit "Add", class: "btn btn-primary" %>
<% end %>

<p class="btn-more-info"><%= link_to "Back to list", lists_path(@list) %></p>

app/views/lists/show.html.erb
<h1><%= @list.name %></h1>
  <div class="btn-style">
    <p><%= link_to "Create a Bookmark",  new_list_bookmark_path(@list), class: 'btn-book' %></p>
  </div>


  <div class="movies-grid">
    <% @list.bookmarks.each do |bookmark| %>
    <div class="box-poster">
      <img class="img-poster" src="<%= bookmark.movie.poster_url %>">
      <p class="movie-path">Movie : <%= bookmark.movie.title %></p>
      <p class="movie-path">Comment : <%= bookmark.comment %></p>
        <p><%= link_to "Delete", bookmark_path(bookmark), data: { turbo_method: :delete, turbo_confirm: "Are you sure" }, class: 'btn-delete'%></p>
    </div>
    <% end %>
  </div>
<p class="btn-more-info"><%= link_to "Back to list", lists_path %></p>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">
      <img src="https://previews.123rf.com/images/sabelskaya/sabelskaya1702/sabelskaya170200383/71715881-cin%C3%A9ma-popcorn-dans-un-grand-seau-ray%C3%A9-rouge-et-blanc-illustration-de-style-croquis-isol%C3%A9-sur-fond-b.jpg" />
</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#">My lists</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">New list</a>
          </li>
          <%# <li class="nav-item dropdown">
            <img class="avatar dropdown-toggle" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="https://kitt.lewagon.com/placeholder/users/ssaunier" />
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
              <a class="dropdown-item" data-turbo-method="delete" href="#">Log out</a>
            </div>
          </li> %>
          <!--li class="nav-item"-->
          <!--/li-->
      </ul>
    </div>
  </div>
</div>